name: wallpaper_hub
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3

  #Freezed Data models
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  freezed_annotation: ^2.0.3

  #State Management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3

  #Firebase
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.4
  firebase_remote_config: ^3.0.4
  firebase_analytics: ^10.0.4

  #URL Launcher
  url_launcher: ^6.1.7

  #Utils
  intl: ^0.17.0

  #DI
  get_it: ^7.2.0

  logging: ^1.0.2

  #Webview
  flutter_inappwebview: ^5.4.3+7

  #Offline DB
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  #network call
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0

  #SVG images
  flutter_svg: ^1.1.6

  #Shimmer effect
  shimmer: ^2.0.0

  #Other
  navigation_history_observer: ^1.1.0

dev_dependencies:

  integration_test:
    sdk: flutter
    
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  hive_generator: ^2.0.0

  #Assest
  flutter_gen: ^5.1.0+1

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  colors:
    inputs:
      - assets/colors/colors.xml
      
  # Optional
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/