// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQbEMIGbmCd0b4gk64yIe_DyF63i3ZSPU',
    appId: '1:448909244836:web:8dcfbe6d56423055fb2931',
    messagingSenderId: '448909244836',
    projectId: 'wallpaper-hub-825e2',
    authDomain: 'wallpaper-hub-825e2.firebaseapp.com',
    storageBucket: 'wallpaper-hub-825e2.appspot.com',
    measurementId: 'G-RYZCFC7WKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChfiec8hdFUu3gqV9wEgnTgmmhngEHFCk',
    appId: '1:448909244836:android:092085d64585ab21fb2931',
    messagingSenderId: '448909244836',
    projectId: 'wallpaper-hub-825e2',
    storageBucket: 'wallpaper-hub-825e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZli-uqXqCMo7X8XzJZzTSVI2pu2JWWLs',
    appId: '1:448909244836:ios:6a637db7ec2895fdfb2931',
    messagingSenderId: '448909244836',
    projectId: 'wallpaper-hub-825e2',
    storageBucket: 'wallpaper-hub-825e2.appspot.com',
    iosClientId: '448909244836-8n3umr9nu3l916c20dh6b10m8mqf5lj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZli-uqXqCMo7X8XzJZzTSVI2pu2JWWLs',
    appId: '1:448909244836:ios:6a637db7ec2895fdfb2931',
    messagingSenderId: '448909244836',
    projectId: 'wallpaper-hub-825e2',
    storageBucket: 'wallpaper-hub-825e2.appspot.com',
    iosClientId: '448909244836-8n3umr9nu3l916c20dh6b10m8mqf5lj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperHub',
  );
}
